import { ApiResponse, JobData } from '@/types/jobs.model'

export const mockJobData: JobData[] = [
  {
    job_id: 'job-001',
    employer_name: 'OpenAI',
    employer_logo: '',
    employer_website: 'https://openai.com',
    employer_company_type: 'Tech',
    employer_linkedin: 'https://linkedin.com/company/openai',
    job_publisher: 'OpenAI Careers',
    job_employment_type: 'FULLTIME',
    job_employment_types: ['FULLTIME'],
    job_employment_type_text: 'Full Time',
    job_title: 'AI Research Engineer',
    job_apply_link: 'https://openai.com/careers/ai-research-engineer',
    job_apply_is_direct: true,
    job_apply_quality_score: 95,
    apply_options: [
      {
        publisher: 'OpenAI',
        apply_link: 'https://openai.com/careers/apply',
        is_direct: true,
      },
    ],
    job_description: 'Work on cutting-edge AI research projects.',
    job_is_remote: true,
    job_posted_human_readable: '2 days ago',
    job_posted_at_timestamp: 1718000000,
    job_posted_at_datetime_utc: '2025-06-13T12:00:00Z',
    job_location: 'San Francisco, CA',
    job_city: 'San Francisco',
    job_state: 'CA',
    job_country: 'USA',
    job_latitude: 37.7749,
    job_longitude: -122.4194,
    job_benefits: ['Healthcare', 'Stock Options', 'Remote Work'],
    job_google_link: 'https://google.com/job-openai',
    job_offer_expiration_datetime_utc: '2025-07-01T12:00:00Z',
    job_offer_expiration_timestamp: 1720000000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 24,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_salary: '$150,000 - $200,000',
    job_min_salary: 150000,
    job_max_salary: 200000,
    job_salary_currency: 'USD',
    job_salary_period: 'year',
    job_highlights: {
      Qualifications: ['PhD in CS or equivalent', '5+ years of experience'],
      Responsibilities: ['Develop AI models', 'Publish research papers'],
      Benefits: ['Free lunch', 'Gym membership'],
    },
    job_job_title: 'AI Research Engineer',
    job_posting_language: 'en',
    job_onet_soc: '15-1221.00',
    job_onet_job_zone: '4',
    job_occupational_categories: ['15-0000.00'],
    job_naics_code: '541715',
    job_naics_name: 'Research and Development in the Physical, Engineering, and Life Sciences',
  },
]

export const mockApiResponse: ApiResponse = {
  status: 'OK',
  request_id: 'mock-request-id-123',
  data: mockJobData,
}
